### ISSUE TITLE
How to add an htaccess file?

### ISSUE THREAD

**Issue by ameenross** [hydephp/hyde#230]
So I want to tell Apache the name of my `404.html` so it won't show Apache's default black&white 404 page. One way to do that is with an `.htaccess` file. Now I tried adding that to the `_media` folder, but the file is not copied to `_site` upon building. And I'd rather not put it in `_site` directly, because someone might decide to remove the entire contents of the folder and then call `hyde build`. Any advice?

**Comment by caendesilva** [comment]
Hi! There are a few ways you could go about this.

You could use a [Custom Build Task](https://hydephp.com/docs/1.x/build-tasks), but that is probably overkill for this.



Instead, I'd recommend that you could update the config/hyde.php file to add this: (Which would allow you to put it in the `_media` folder.

```php
'media_extensions' => array_merge(\Hyde\Support\Filesystem\MediaFile::EXTENSIONS, ['.htaccess']),
```

**However**, I just confirmed that this does not work, so I'll make a patch this afternoon if you think this could work for you?

**Comment by ameenross** [comment]
Ah, right. Sure, that would work fine for me. Thanks!

**Comment by ameenross** [comment]
So I think I solved it with a custom build task. I made a folder `_extra`, the contents of which will simply be merged into `_site`. Here's my code, which might not be ideal for everyone, but is sufficient for me.

```php
<?php namespace App\Actions;

use Hyde\Framework\Features\BuildTasks\PostBuildTask;
use Hyde\Hyde;

class CustomBuildTask extends PostBuildTask
{
    public function handle(): void
    {
        // Copy all the files from the `_extra` folder verbatim.
        $destination = Hyde::getOutputDirectory();
        `cp -r _extra/* $destination`;

        // Also copy hidden files.
        `cp -r _extra/.??* $destination`;
    }
}
```

**Comment by caendesilva** [comment]
> Ah, right. Sure, that would work fine for me. Thanks!
> 
> Wait, but actually... wouldn't that mean the `.htaccess` file is added to `_site/media`? It should be in the root... darn.

You are right. I was in a rush to leave and totally forgot about that. I'm thinking what the best way to do this is, as I think this is something Hyde should support.

What do you think about having it so that a `.htaccess` file in the `_pages/` directory is copied to `_site/`? I should mention that when Hyde empties the directory during a site build, it takes care to not delete special files, so it is safe to put a `.htaccess` directly in the `_site/` directory, unless you think someone may manually remove it.

Here is the code that handles emptying the output directory in case you want to check out the exact rules for this.
https://github.com/hydephp/framework/blob/7cdea1f7e1c535254acd2617c2cdad3e20c1e914/src/Framework/Actions/PreBuildTasks/CleanSiteDirectory.php#L24-L27

**Comment by ameenross** [comment]
> [...] I think this is something Hyde should support.

Yes, I expected it to be supported. And I normally don't care too much about lots of features so I probably won't be the only one.

> What do you think about having it so that a `.htaccess` file in the `_pages/` directory is copied to `_site/`?

Not sure. It's not really a page, but if that's the (documented) way, then it *is* a solution.

> unless you think someone may manually remove it.

Yes, I wouldn't want `rm -rf _site` to cause problems. Also, I just `.gitignore`d my entire `_site` folder, because I'd like to setup a build script along these lines:

- clear `_site`
- `hyde build`
- deploy

Simply removing all build artifacts is pretty common, and if there's a certain directory for it then it becomes really easy to do as well. It's kind of a developer's expectation that nothing breaks in that case.

**Comment by caendesilva** [comment]
Thank you for the response! As you have a workaround in the meantime, I'm going to think a bit about what the best way to implement this is. I'll keep this issue open until then. Thank you for bringing this to my attention, as I somehow overlooked this!

**Comment by ameenross** [comment]
Thanks for your responses.

Although Linux fs read cache taking care of reading the `.htaccess` file, so the performance hit is practically 0 nowadays.

**Comment by caendesilva** [comment]
Nice! Then I learned something new today!

**Comment by caendesilva** [comment]
Okay, so I've done some thinking about this. And I think the recommended way to add a `.htaccess` file in HydePHP should be to add it to `_site/.htaccess` as Hyde will not remove such files during the build process. I also personally like gitignoring the build directory, but it's always easy to add an exclude so that the `.htaccess` file is version controlled.

I do not think it is a standard use case to have it so that others can accidentally remove important files. And for such cases, I think your proposed buildtask solution is sufficient.

I am always open to being wrong, and am happy to revisit the matter if I get an epiphany later, of if someone has a good idea on how to handle this!

**Comment by ameenross** [comment]
I prefer my solution, but thanks for your consideration. If anyone else has the same (or similar) problem, hopefully this issue will help anyway.
