### ISSUE TITLE
Source and output directory for media

### ISSUE THREAD

**Issue by Fot0n** [hydephp/hyde#238]
Hello! Thanks for the great project! As a wish. I am using a single Hyde instance to generate multiple sites. To do this, in .env and config/hyde.php I pass variables containing paths to the content and templates of the site. This does not work with media due to the fact that the source and output paths are the same setting. I'm making a temporary soft link to a directory with media files, but it's not too convenient. It would be great if you split the source and output directories, as is done for text content.

**Comment by caendesilva** [comment]
Hey there, super glad to hear you are enjoying Hyde!

May I ask what the reason behind wanting to use a single Hyde instance is? The way Hyde is designed is for it to be installed on a per-project basis so that each site and the dependencies therein are isolated and can work independently from each other. The reason I ask is to make sure we can solve the correct problem 🙂

**Comment by Fot0n** [comment]
> Hey there, super glad to hear you are enjoying Hyde!

Really. Even commercial projects do not often boast such thoughtful documentation.

> May I ask what the reason behind wanting to use a single Hyde instance is?

These sites are created to test hypotheses about Google, they are similar to each other within the same group and are no longer updated after generation (exceptions are rare), so it does not make sense to have a separate Hyde instance.

**Comment by caendesilva** [comment]
> Really. Even commercial projects do not often boast such thoughtful documentation.

❤❤❤

> These sites are created to test hypotheses about Google, they are similar to each other within the same group and are no longer updated after generation (exceptions are rare), so it does not make sense to have a separate Hyde instance.

I understand! Would it be possible for you to give me read access to the repository, or for one with a similar setup, so I can better visualise what you're doing and what the best way for a workaround or possible feature implementation could be? Also, what kind of media files are you using for your project? 

In the meantime, here are some general tips that may help depending on what you need to do
- If you just need the default app styles and don't need to customize them, you can load them from our CDN, instead of having a local CSS file.
- You can use `PostBuildTasks` to do stuff upon each build
- You can create `HydeExtensions` to hook into the Hyde Autodiscovery Process

**Comment by Fot0n** [comment]
> You can use PostBuildTasks to do stuff upon each build

The Build Tasks is what I need. Implemented the changes before the build and rolled back after. Thanks for the help! I'm sorry for taking up your time instead of delving deeper.

**Comment by caendesilva** [comment]
> > You can use PostBuildTasks to do stuff upon each build
> 
> The Build Tasks is what I need. Implemented the changes before the build and rolled back after. Thanks for the help! I'm sorry for taking up your time instead of delving deeper.

It's no problem at all! The reason I asked so many questions was to get a better idea of what you were trying to do, as I suspected that we maybe already supported it. If you run into any issues in the future, don't hesitate to reach back out. I'm always happy to hear from users and help the best I can. Take care and have fun with Hyde!
