### ISSUE TITLE
Autodiscover layouts in resources directory

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#258]
Would seem to make sense if we could create our own views that would automatically overwrite the defaults. Say, if we created a `/resources/views/layouts/app.blade.php` file, Hyde would consider that our app view and disregard Hyde's defaults. The way it is now is somewhat confusing.

With that said, I only discovered Hyde 15 minutes ago and am getting the impression this is exactly what I've been looking for! :)

_Originally posted by @timgavin in https://github.com/hydephp/hyde/discussions/225#discussioncomment-9782914_

**Comment by caendesilva** [comment]
Actually, the way you describe it, this sounds exactly like the HydePHP design:

> Say, if we created a /resources/views/layouts/app.blade.php file, Hyde would consider that our app view and disregard Hyde's defaults.

I'm gonna convert this to an issue for implementation! Possibly this will happen in v2.x but we'll see. Thanks again for the detailed feedback and for trying Hyde!


_Originally posted by @caendesilva in https://github.com/hydephp/hyde/discussions/225#discussioncomment-9782974_

**Comment by caendesilva** [comment]
I'm thinking this could apply to all root-level layouts, like the app layout and the base page layouts. In order to reduce complexity, it may make sense to keep the Laravel way of overriding individual components through the vendor view system.

**Comment by timgavin** [comment]
Yeah. I'm currently building a form library that will allow users to overwrite the default views simply by adding their own views into an assets directory. If the `/myAssets/views/`directory exists, those files are used and the framework's defaults are ignored. Could be the same for Hyde, where if anything exists in the views directory, use those files instead. Makes it super easy for the user because they don't even have to think about it. I spent 10 minutes looking through the documentation trying to find out how to add views only to end end up at the repo seeing if anyone else had this problem or if I was just stupid :)

**Comment by caendesilva** [comment]
> Edit: definitely keep the Laravel way, as that's exactly what I was expecting as a user. Was hoping to only spend 2 minutes with the docs and then get on to building my site. The Laravel way would definitely enable that. To me: docs are only for when you can't figure it out yourself ;)

Okay, shall we close this for now then? Might be easier to follow the conventions instead of having two options. In either case, feel free to let me know any time you run into an issue or have suggestions!
