### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by echo-LuGuang** [hydephp/hyde#269]
I discovered this great project in `Laravel News` today, but after using it, I found that it is not friendly to Chinese support.

<img width="585" alt="image" src="https://github.com/user-attachments/assets/07cda1c8-f92a-4e48-8c31-809182281b74">
<img width="406" alt="image" src="https://github.com/user-attachments/assets/94a72f4b-7b52-4478-aedd-42d549e3f4e7">

``` php
// CreatesNewMarkdownPostFile.php

public function __construct(string $title, ?string $description, ?string $category, ?string $author, ?string $date = null, ?string $customContent = null)
    {
        $this->title = $title;
        $this->description = $description ?? 'A short description used in previews and SEO';
        $this->category = $category ?? 'blog';
        $this->author = $author ?? 'default';
        $this->customContent = $customContent;

        $this->date = Carbon::make($date ?? Carbon::now())->format('Y-m-d H:i');
        $this->identifier = Str::slug($title);   // <--  here
    }
```

```php
dump(Str::slug('你好世界', language: 'zh-CN')); // ✅
dump(Str::slug('你好世界')); // ❌

```
```[tasklist]
### Tasks
```

**Comment by caendesilva** [comment]
@echo-LuGuang Two follow up questions: 

1. What is your expected behaviour here? We really don't want the filename to be empty of course, but should it be transliterated to ASCII, or should we use the Chinese character directly? I'm not sure what the URL support is for that. 

2. I see that specifying the language in the `Str::slug` call returns `ni-hao-shi-jie`, so if we go with the transliteration route, I'm thinking about the best implementation route. I think we could either always transliterate input before making slugs, or we use the app language as the language parameter, but that would require configuration on your part. Do you have a preference here?

**Comment by echo-LuGuang** [comment]
1. Yes, I would like to transliterate it into ASCII, Instead of the original Chinese string.
2. I think using application languages as language parameters is great.

Thank you. ❤️

**Comment by caendesilva** [comment]
Hey @echo-LuGuang! Just wanted to let you know that this has been fixed in https://github.com/hydephp/framework/releases/tag/v1.7.5.

Thank you so much for the clear reproduction steps and implementation ideas - it really made it so much easier to fix this issue. Please let me know if the fix works for you, and if you find anything else we can improve. 🎩
